Repository silverstripe/cwp, pull requests merged in 2018-04, with the labels that each got.

#62 DOCS Update reference to CWP basic recipe on GitLab to GitHub
  docs/en/01_Working_with_projects/00_Setting_up_a_development_environment.md
  docs/en/01_Working_with_projects/01_Setting_up_your_project.md
  docs/en/01_Working_with_projects/02_Maintaining_your_code.md
  docs/en/01_Working_with_projects/03_Recipes_and_supported_modules.md
  docs/en/01_Working_with_projects/05_Customising_the_starter_theme.md
  docs/en/01_Working_with_projects/08_Upgrading.md
  docs/en/01_Working_with_projects/14_Using_the_Watea_theme.md
  docs/en/02_Features/00_Pre_configuration.md
  docs/en/02_Features/01_Solr_search/00_Configuration.md
  docs/en/02_Features/01_Solr_search/06_Tuning_the_search_results.md
  docs/en/03_How_tos/preparing_your_site_for_active_dr.md
  docs/en/05_Releases_and_changelogs/cwp_recipe_basic_1.6.0.md
Labels: affects/v3, type/docs

#64 Only add File_ShowInSearch when File class in query
  code/search/CwpSearchEngine.php
Labels: affects/v3, change/patch

#65 Remove fulltextsearch from Travis tests, not required any more
  .travis.yml
Labels: affects/v4

#56 FIX Remove rogue nbsp; from Start Time field labels
  src/PageTypes/EventPage.php
Labels: affects/v4, change/patch

#59 FIX Switch example date format to match HTML5 datetime field format
  lang/en.yml
  src/PageTypes/DatedUpdateHolderController.php
Labels: affects/v4, change/patch

#70 DOCS Clarify intent of BasePage in PHPDoc and encourage extending Page
  src/PageTypes/BasePage.php
Labels: affects/v4, change/patch

#73 fix regex issue in performance docs
  docs/en/03_How_tos/caching.md
Labels: affects/v3, type/docs

#74 fix regex in performance guide htaccess rules
  docs/en/04_Performance_Guide/02_HTTP_Caching.md
Labels: affects/v3, type/docs

#71 FIX Unentice direct BasePage creation in the CMS
  src/Extensions/TaxonomyTermExtension.php
Labels: affects/v4, change/patch

#76 DOCS Add note to upgrade guide about mandatory public webroot, and link from upgrade guide
  docs/en/01_Working_with_projects/08_Upgrading.md
  docs/en/05_Releases_and_changelogs/cwp_recipe_basic_2.0.0.md
Labels: affects/v4, type/docs
