Repository silverstripe/cwp, pull requests merged in 2018-06, with the labels that each got.

#92 Fix broken link
  docs/en/01_Working_with_projects/06_Working_with_modules.md
Labels: affects/v3, type/docs

#95 Fix broken links in developer docs
  docs/en/01_Working_with_projects/03_Recipes_and_supported_modules.md
  docs/en/01_Working_with_projects/04_Customising_the_default_functionality.md
  docs/en/01_Working_with_projects/08_Upgrading.md
  docs/en/01_Working_with_projects/11_Infrastructural_considerations.md
  docs/en/02_Features/01_Solr_search/00_Configuration.md
  docs/en/02_Features/active_directory_single_sign_on.md
  docs/en/02_Features/creating_forms.md
  docs/en/02_Features/realme_authentication.md
  docs/en/03_How_tos/creating_repositories.md
  docs/en/03_How_tos/migrate_git_repo_to_github.md
Labels: affects/v4, type/docs

#97 DOCS Add maintenance, security and version checker to the recipes
  docs/en/01_Working_with_projects/03_Recipes_and_supported_modules.md
Labels: affects/v4, type/docs

#107 Add statement about testing for server/config issues
  docs/en/02_Features/01_Solr_search/00_Configuration.md
Labels: affects/v4, type/docs

#116 FIX Use correct TinyMCE skin in CWP CMS instances, remove closure scope (unneeded)
  .travis.yml
  _config.php
Labels: affects/v4, change/patch

#125 FIX Maintenance module extension now provides CWP proxy information for HTTP requests
  _config/maintenance.yml
  src/Extensions/MaintenanceProxyExtension.php
Labels: affects/v4, change/patch

#127 FIX Maintenance module extension now provides CWP proxy information for HTTP requests
  _config/maintenance.yml
  code/extensions/MaintenanceProxyExtension.php
Labels: affects/v3, change/patch

#128 FIX Remove COMPOSER_HOME definition, update-checker module now does this itself
  src/Extensions/MaintenanceProxyExtension.php
Labels: affects/v4, change/patch

#132 FIX Maintenance module configuration for CWP is now in place
  _config/maintenance.yml
Labels: affects/v4, change/patch
